# Generated by Django 5.2.7 on 2025-10-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_to_sale', models.BooleanField()),
                ('name', models.CharField(max_length=25)),
                ('owner_mail', models.EmailField(max_length=254, unique=True)),
                ('price', models.FloatField()),
                ('no_of_bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('built_date', models.DateField()),
                ('registration_time', models.TimeField()),
                ('location', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
