# Generated by Django 5.2.7 on 2025-10-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='built_date',
        ),
    ]
