# Generated by Django 5.2.7 on 2025-10-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_house_built_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='registration_time',
        ),
    ]
