# Generated by Django 5.2.7 on 2025-10-29 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_house_registration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='purchasing_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 9, 25, 48, 906703)),
        ),
        migrations.AddField(
            model_name='house',
            name='registration_time',
            field=models.TimeField(default=datetime.time(9, 25, 48, 906813)),
        ),
    ]
