# Generated by Django 5.2.7 on 2025-10-29 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_house_purchasing_date_house_registration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='purchasing_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 11, 35, 17, 655604)),
        ),
        migrations.AlterField(
            model_name='house',
            name='registration_time',
            field=models.TimeField(default=datetime.time(11, 35, 17, 655766)),
        ),
    ]
