# Generated by Django 5.2.7 on 2025-10-29 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_house_purchasing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='purchasing_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 11, 41, 59, 352061)),
        ),
        migrations.AlterField(
            model_name='house',
            name='registration_time',
            field=models.TimeField(default=datetime.time(11, 41, 59, 352148)),
        ),
    ]
