# Generated by Django 5.2.7 on 2025-10-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_house_purchasing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='purchasing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='registration_time',
            field=models.TimeField(null=True),
        ),
    ]
