# Generated by Django 5.2.7 on 2025-10-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_house_purchasing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
