# Generated by Django 5.2.7 on 2025-10-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
